[language-server]
haskell-language-server = { command = "haskell-language-server-wrapper", args = ["--lsp"] }

[[language]]
name = "haskell"
file-types = ["hs", "hs-boot", "hsc"]
workspace-lsp-roots = ["Setup.hs", "stack.yaml", "cabal.project"]
language-servers = [ "haskell-language-server" ]

[[grammar]]
name = "haskell"
source = { git = "https://github.com/tree-sitter/tree-sitter-haskell", rev = "d7ac98f49e3ed7e17541256fe3881a967d7ffdd3" }

[[language]]
name = "cabal"
file-types = [ "cabal" ]
workspace-lsp-roots = ["cabal.project", "Setup.hs"]
language-servers = [ "haskell-language-server" ]
